services:
  - type: web
    name: ssc-election-system
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: python -m gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: .onrender.com
